import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillGithub,
  AiFillInstagram
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/zeheer.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/turfWebsite.png";
import web2 from "../public/fashionWebsite.png";
import web3 from "../public/urlWebsite.png";
import web4 from "../public/netflixWebsite.png";
import web5 from "../public/todoWebsite.png";
import web6 from "../public/olxCloneWebsite.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Mohammed</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Mohammed</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://drive.google.com/file/d/1e49ZT5TLLqbSPl3KcOmZUOvxJ0H6JCy0/view?usp=sharing"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              MOHAMMED
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              MERN Stack Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              {/* I am Mohammed, a proficient MERN-stack developer specializing in
              NodeJs and React. Committed to delivering top-notch solutions, I
              am driven by my passion for technology. I'm on the lookout for a
              position that aligns with my skills and aspirations, where I can
              make a valuable impact.  */}
              {/* I am Mohammed, a proficient MERN-stack developer specializing in
              NodeJs and React. I have a passion for leveraging
              technology to craft exceptional solutions. Presently, I am
              actively seeking a position that aligns with my skills and
              aspirations, where I can truly make a positive impact. */}
              I'm Mohammed, a skilled MERN-stack developer with expertise in
              NodeJs and React. I'm passionate about using technology to create
              exceptional solutions. Currently seeking a role where I can make a
              meaningful impact.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              {/* <AiFillTwitterCircle />
              <AiFillLinkedin />
              <AiFillYoutube /> */}

              <a
                href="https://github.com/Mohammedzeheer"
                target="_blank"
                rel="noopener noreferrer"
              >
                <AiFillGithub />
              </a>

              <a
                href="https://www.linkedin.com/in/mohammedzeheer/"
                target="_blank"
                rel="noopener noreferrer"
              >
                <AiFillLinkedin />
              </a>

              <a
                href="https://www.instagram.com/zaheer_.zak/"
                target="_blank"
                rel="noopener noreferrer"
              >
                <AiFillInstagram />
              </a>
              {/* <AiFillYoutube />  */}
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-80 md:w-80">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>

        {/* <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Indesign</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Code your dream project
              </h3>
              <p className="py-2">
                Do you have an idea for your next great website? Let's make it a
                reality.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Indesign</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Consulting</h3>
              <p className="py-2">
                Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Indesign</p>
            </div>
          </div>
        </section> */}

        <section className="py-10">
          <div>
            <h3 className="text-3xl font-bold py-1 dark:text-white ">
              PROJECTS
            </h3>
            <p className="text-LG py-2 leading-8 text-gray-800 dark:text-gray-200">
              <span className="text-teal-500"> Works </span>, I'm most proud of
            </p>

            {/* <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Works, I'm most proud of
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p> */}
            {/* <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p> */}
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            {/* <div className="basis-1/3 flex-1">
              <a href="https://aoneturf.netlify.app/">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"50%"}
                  layout="responsive"
                  src={web1}
                />
              </a>
            </div> */}

            <div className="basis-1/3 flex-1">
              <a
                href="https://aoneturf.netlify.app/"
                className="relative group"
              >
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"50%"}
                  layout="responsive"
                  src={web1}
                />
                <div className="hidden group-hover:flex justify-center items-center absolute inset-0 bg-black bg-opacity-50">
                  <p className="text-white text-2xl">Turf Booking</p>
                </div>
              </a>
            </div>

            {/* <div className="basis-1/3 flex-1">
              <a href="https://a1fashion.online/">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"50%"}
                  layout="responsive"
                  src={web2}
                />
              </a>
            </div> */}

            <div className="basis-1/3 flex-1">
              <a
                href="https://a1fashion.online/"
                className="relative group"
              >
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"50%"}
                  layout="responsive"
                  src={web2}
                />
                <div className="hidden group-hover:flex justify-center items-center absolute inset-0 bg-black bg-opacity-50">
                  <p className="text-white text-2xl">Ecommerce - Fashion</p>
                </div>
              </a>
            </div>
            {/* <div className="basis-1/3 flex-1">
              <a href="https://url-shortner-seven-virid.vercel.app/">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"50%"}
                  layout="responsive"
                  src={web3}
                />
              </a>
            </div> */}

            <div className="basis-1/3 flex-1">
              <a
                href="https://url-shortner-seven-virid.vercel.app/"
                className="relative group"
              >
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"50%"}
                  layout="responsive"
                  src={web3}
                />
                <div className="hidden group-hover:flex justify-center items-center absolute inset-0 bg-black bg-opacity-50">
                  <p className="text-white text-2xl">Url Shortner</p>
                </div>
              </a>
            </div>


            {/* <div className="basis-1/3 flex-1">
              <a href="https://charming-puffpuff-5df4f3.netlify.app/">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"50%"}
                  layout="responsive"
                  src={web4}
                />
              </a>
            </div> */}

            <div className="basis-1/3 flex-1">
              <a
                href="https://charming-puffpuff-5df4f3.netlify.app/"
                className="relative group"
              >
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"50%"}
                  layout="responsive"
                  src={web4}
                />
                <div className="hidden group-hover:flex justify-center items-center absolute inset-0 bg-black bg-opacity-50">
                  <p className="text-white text-2xl">Netflix clone</p>
                </div>
              </a>
            </div>

            {/* <div className="basis-1/3 flex-1">
            <a href="https://timely-travesseiro-23afd1.netlify.app/">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"50%"}
                layout="responsive"
                src={web5}
              />
              </a>
            </div> */}

            <div className="basis-1/3 flex-1">
              <a
                href="https://timely-travesseiro-23afd1.netlify.app/"
                className="relative group"
              >
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"50%"}
                  layout="responsive"
                  src={web5}
                />
                <div className="hidden group-hover:flex justify-center items-center absolute inset-0 bg-black bg-opacity-50">
                  <p className="text-white text-2xl">ToDo List</p>
                </div>
              </a>
            </div>

            {/* <div className="basis-1/3 flex-1">
              <a href="https://fir-158f0.web.app/">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"50%"}
                  layout="responsive"
                  src={web6}
                />
              </a>
            </div> */}

            <div className="basis-1/3 flex-1">
              <a
                href="https://fir-158f0.web.app/"
                className="relative group"
              >
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"50%"}
                  layout="responsive"
                  src={web6}
                />
                <div className="hidden group-hover:flex justify-center items-center absolute inset-0 bg-black bg-opacity-50">
                  <p className="text-white text-2xl">Olx Clone</p>
                </div>
              </a>
            </div>
           
          </div>
        </section>

        <div>
          <div className="text-center p-10 py-10">
            <h3 className="text-2xl font-poppins py-2 text-teal-500 dark:text-white md:text-3xl">
              Contact
            </h3>
            <p className="text-md font-mono py-2 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              zeheerzak@gmail.com | +91 9995088067
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}
